CREATE TABLE IF NOT EXISTS `news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `head` TINYTEXT CHARACTER SET 'utf8' NOT NULL,
  `briefly` TEXT CHARACTER SET 'utf8' NOT NULL,
  `full` TEXT CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;