INSERT INTO `group_to_permission` (`group`, `permission`) VALUES ('1', '1');
INSERT INTO `group_to_permission` (`group`, `permission`) VALUES ('1', '2');
INSERT INTO `group_to_permission` (`group`, `permission`) VALUES ('1', '3');
INSERT INTO `group_to_permission` (`group`, `permission`) VALUES ('1', '4');
INSERT INTO `group_to_permission` (`group`, `permission`) VALUES ('1', '5');
INSERT INTO `group_to_permission` (`group`, `permission`) VALUES ('1', '6');
INSERT INTO `group_to_permission` (`group`, `permission`) VALUES ('1', '7');
INSERT INTO `group_to_permission` (`group`, `permission`) VALUES ('1', '8');
INSERT INTO `group_to_permission` (`group`, `permission`) VALUES ('1', '9');